#!/usr/bin/env python3
r"""
Generate one UnrealScript subclass per Minecraft block.

This script NEVER modifies Classes\MinecraftBlock.uc.

Expected layout:

    MinecraftBlocks\
        generate_classes.py
        blocklist_names.txt
        generated_manifest.json   (optional)
        Textures\
            MCStone.pcx
            MCGrass.pcx
            ...
        Classes\
            MinecraftBlock.uc
            ...

Each generated class gets its own texture import, for example:

    class Grass extends MinecraftBlock;

    #exec TEXTURE IMPORT NAME=MCGrass FILE="Textures\MCGrass.pcx" GROUP=Minecraft

    defaultproperties
    {
        Skin=Texture'MinecraftBlocks.Minecraft.MCGrass'
    }

Run:
    python generate_classes.py
"""

from __future__ import annotations

import json
import re
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent
CLASSES_DIR = BASE_DIR / "Classes"
TEXTURES_DIR = BASE_DIR / "Textures"

BLOCKLIST_FILE = BASE_DIR / "blocklist_names.txt"
TEXTUREMAP_FILE = BASE_DIR / "texturemap.json"
MANIFEST_FILE = BASE_DIR / "generated_manifest.json"

PACKAGE_NAME = "MinecraftBlocks"
TEXTURE_GROUP = "Minecraft"

GENERATED_CLASS_MARKER = "// AUTO-GENERATED BY generate_classes.py"


def load_block_names() -> list[str]:
    if BLOCKLIST_FILE.exists():
        return [
            line.strip()
            for line in BLOCKLIST_FILE.read_text(encoding="utf-8").splitlines()
            if line.strip()
        ]

    # Fallback: use the keys from texturemap.json.
    if TEXTUREMAP_FILE.exists():
        data = json.loads(TEXTUREMAP_FILE.read_text(encoding="utf-8"))
        blocks = data.get("blocks", {})
        if blocks:
            return list(blocks.keys())

    raise FileNotFoundError(
        "Could not find blocklist_names.txt or a usable texturemap.json"
    )


def load_manifest() -> dict:
    if not MANIFEST_FILE.exists():
        return {}

    try:
        return json.loads(MANIFEST_FILE.read_text(encoding="utf-8"))
    except Exception as exc:
        print(f"WARNING: Could not read {MANIFEST_FILE.name}: {exc}")
        return {}


def is_valid_class_name(name: str) -> bool:
    return bool(re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name))


def texture_name(block_name: str) -> str:
    return f"MC{block_name}"


def texture_filename(block_name: str) -> str:
    return f"{texture_name(block_name)}.pcx"


def block_is_masked(block_name: str, manifest: dict) -> bool:
    entry = manifest.get("blocks", {}).get(block_name, {})
    return bool(entry.get("transparent", False))


def generate_class(block_name: str, masked: bool) -> str:
    tex_name = texture_name(block_name)

    lines = [
        GENERATED_CLASS_MARKER,
        f"class {block_name} extends MinecraftBlock;",
        "",
        f'#exec TEXTURE IMPORT NAME={tex_name} FILE="Textures\\{tex_name}.pcx" GROUP={TEXTURE_GROUP}',
        "",
        "defaultproperties",
        "{",
        f"    Skin=Texture'{PACKAGE_NAME}.{TEXTURE_GROUP}.{tex_name}'",
    ]

    if masked:
        lines.append("    Style=STY_Masked")

    lines += [
        "}",
        "",
    ]

    return "\n".join(lines)


def main() -> int:
    try:
        block_names = load_block_names()
    except Exception as exc:
        print(f"ERROR: {exc}")
        return 1

    invalid = [name for name in block_names if not is_valid_class_name(name)]
    if invalid:
        print("ERROR: Invalid UnrealScript class names:")
        for name in invalid:
            print(f"  {name}")
        return 1

    duplicates = sorted({
        name for name in block_names
        if block_names.count(name) > 1
    })
    if duplicates:
        print("ERROR: Duplicate block names:")
        for name in duplicates:
            print(f"  {name}")
        return 1

    missing = [
        texture_filename(name)
        for name in block_names
        if not (TEXTURES_DIR / texture_filename(name)).exists()
    ]
    if missing:
        print(f"ERROR: {len(missing)} texture file(s) are missing:")
        for filename in missing[:30]:
            print(f"  {filename}")
        if len(missing) > 30:
            print(f"  ... and {len(missing) - 30} more")
        print()
        print("Run generate_textures.py first.")
        return 1

    CLASSES_DIR.mkdir(parents=True, exist_ok=True)
    manifest = load_manifest()

    generated = 0
    masked_count = 0

    for block_name in block_names:
        out_file = CLASSES_DIR / f"{block_name}.uc"

        # Do not overwrite hand-written classes accidentally.
        if out_file.exists():
            existing = out_file.read_text(encoding="utf-8", errors="replace")
            if GENERATED_CLASS_MARKER not in existing:
                print(f"ERROR: Refusing to overwrite non-generated class: {out_file}")
                return 1

        masked = block_is_masked(block_name, manifest)
        if masked:
            masked_count += 1

        out_file.write_text(
            generate_class(block_name, masked),
            encoding="utf-8"
        )
        generated += 1

    print(f"Generated {generated} block classes in:")
    print(f"  {CLASSES_DIR}")
    print()
    print("MinecraftBlock.uc was NOT modified.")
    print(f"Masked subclasses: {masked_count}")
    print()
    print("Example:")
    print(f"  summon {PACKAGE_NAME}.Grass")
    print()
    print("You can now run ucc make.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
