// AUTO-GENERATED BY generate_classes.py
class AcaciaPlanks extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCAcaciaPlanks FILE="Textures\MCAcaciaPlanks.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCAcaciaPlanks'
    PlaceSoundFamily=Wood
}
