// AUTO-GENERATED BY generate_classes.py
class AcaciaLeaves extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCAcaciaLeaves FILE="Textures\MCAcaciaLeaves.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCAcaciaLeaves'
    PlaceSoundFamily=Grass
    Style=STY_Masked
}
