// AUTO-GENERATED BY generate_classes.py
class AcaciaLog extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCAcaciaLog FILE="Textures\MCAcaciaLog.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCAcaciaLog'
}
