// AUTO-GENERATED BY generate_classes.py
class Andesite extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCAndesite FILE="Textures\MCAndesite.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCAndesite'
    PlaceSoundFamily=Stone
}
