// AUTO-GENERATED BY generate_classes.py
class Bedrock extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBedrock FILE="Textures\MCBedrock.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBedrock'
    PlaceSoundFamily=Stone
}
