// AUTO-GENERATED BY generate_classes.py
class BirchLeaves extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBirchLeaves FILE="Textures\MCBirchLeaves.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBirchLeaves'
    Style=STY_Masked
}
