// AUTO-GENERATED BY generate_classes.py
class BirchLog extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBirchLog FILE="Textures\MCBirchLog.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBirchLog'
}
