// AUTO-GENERATED BY generate_classes.py
class BirchPlanks extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBirchPlanks FILE="Textures\MCBirchPlanks.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBirchPlanks'
}
