// AUTO-GENERATED BY generate_classes.py
class BlackStainedGlass extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBlackStainedGlass FILE="Textures\MCBlackStainedGlass.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBlackStainedGlass'
    Style=STY_Masked
}
