// AUTO-GENERATED BY generate_classes.py
class BlackTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBlackTerracotta FILE="Textures\MCBlackTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBlackTerracotta'
}
