// AUTO-GENERATED BY generate_classes.py
class BlackWool extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBlackWool FILE="Textures\MCBlackWool.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBlackWool'
    PlaceSoundFamily=Cloth
}
