// AUTO-GENERATED BY generate_classes.py
class BlackShulkerBox extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBlackShulkerBox FILE="Textures\MCBlackShulkerBox.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBlackShulkerBox'
}
