// AUTO-GENERATED BY generate_classes.py
class BlackConcrete extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBlackConcrete FILE="Textures\MCBlackConcrete.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBlackConcrete'
}
