// AUTO-GENERATED BY generate_classes.py
class BlackConcretePowder extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBlackConcretePowder FILE="Textures\MCBlackConcretePowder.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBlackConcretePowder'
}
