// AUTO-GENERATED BY generate_classes.py
class BlackGlazedTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBlackGlazedTerracotta FILE="Textures\MCBlackGlazedTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBlackGlazedTerracotta'
    PlaceSoundFamily=Stone
}
