// AUTO-GENERATED BY generate_classes.py
class BlueConcretePowder extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBlueConcretePowder FILE="Textures\MCBlueConcretePowder.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBlueConcretePowder'
}
