// AUTO-GENERATED BY generate_classes.py
class BlueGlazedTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBlueGlazedTerracotta FILE="Textures\MCBlueGlazedTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBlueGlazedTerracotta'
}
