// AUTO-GENERATED BY generate_classes.py
class BlueShulkerBox extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBlueShulkerBox FILE="Textures\MCBlueShulkerBox.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBlueShulkerBox'
}
