// AUTO-GENERATED BY generate_classes.py
class BlueTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBlueTerracotta FILE="Textures\MCBlueTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBlueTerracotta'
}
