// AUTO-GENERATED BY generate_classes.py
class BlueConcrete extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBlueConcrete FILE="Textures\MCBlueConcrete.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBlueConcrete'
    PlaceSoundFamily=Stone
}
