// AUTO-GENERATED BY generate_classes.py
class BlueStainedGlass extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBlueStainedGlass FILE="Textures\MCBlueStainedGlass.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBlueStainedGlass'
    PlaceSoundFamily=Stone
    Style=STY_Masked
}
