// AUTO-GENERATED BY generate_classes.py
class BlueWool extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBlueWool FILE="Textures\MCBlueWool.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBlueWool'
}
