// AUTO-GENERATED BY generate_classes.py
class BoneBlock extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBoneBlock FILE="Textures\MCBoneBlock.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBoneBlock'
    PlaceSoundFamily=Stone
}
