// AUTO-GENERATED BY generate_classes.py
class Bookshelf extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBookshelf FILE="Textures\MCBookshelf.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBookshelf'
}
