// AUTO-GENERATED BY generate_classes.py
class Bricks extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBricks FILE="Textures\MCBricks.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBricks'
}
