// AUTO-GENERATED BY generate_classes.py
class BrownStainedGlass extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBrownStainedGlass FILE="Textures\MCBrownStainedGlass.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBrownStainedGlass'
    PlaceSoundFamily=Stone
    Style=STY_Masked
}
