// AUTO-GENERATED BY generate_classes.py
class BrownShulkerBox extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBrownShulkerBox FILE="Textures\MCBrownShulkerBox.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBrownShulkerBox'
}
