// AUTO-GENERATED BY generate_classes.py
class BrownMushroomBlock extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBrownMushroomBlock FILE="Textures\MCBrownMushroomBlock.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBrownMushroomBlock'
    PlaceSoundFamily=Grass
}
