// AUTO-GENERATED BY generate_classes.py
class BrownWool extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBrownWool FILE="Textures\MCBrownWool.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBrownWool'
}
