// AUTO-GENERATED BY generate_classes.py
class BrownTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBrownTerracotta FILE="Textures\MCBrownTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBrownTerracotta'
    PlaceSoundFamily=Stone
}
