// AUTO-GENERATED BY generate_classes.py
class BrownGlazedTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBrownGlazedTerracotta FILE="Textures\MCBrownGlazedTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBrownGlazedTerracotta'
}
