// AUTO-GENERATED BY generate_classes.py
class BrownConcretePowder extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBrownConcretePowder FILE="Textures\MCBrownConcretePowder.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBrownConcretePowder'
    PlaceSoundFamily=Sand
}
