// AUTO-GENERATED BY generate_classes.py
class BrownConcrete extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBrownConcrete FILE="Textures\MCBrownConcrete.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBrownConcrete'
}
