// AUTO-GENERATED BY generate_classes.py
class BurningFurnace extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCBurningFurnace FILE="Textures\MCBurningFurnace.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCBurningFurnace'
}
