// AUTO-GENERATED BY generate_classes.py
class ChainCommandBlock extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCChainCommandBlock FILE="Textures\MCChainCommandBlock.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCChainCommandBlock'
    PlaceSoundFamily=Stone
}
