// AUTO-GENERATED BY generate_classes.py
class ChiseledRedSandstone extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCChiseledRedSandstone FILE="Textures\MCChiseledRedSandstone.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCChiseledRedSandstone'
}
