// AUTO-GENERATED BY generate_classes.py
class ChiseledQuartzBlock extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCChiseledQuartzBlock FILE="Textures\MCChiseledQuartzBlock.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCChiseledQuartzBlock'
    PlaceSoundFamily=Stone
}
