// AUTO-GENERATED BY generate_classes.py
class ChiseledStoneBricks extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCChiseledStoneBricks FILE="Textures\MCChiseledStoneBricks.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCChiseledStoneBricks'
}
