// AUTO-GENERATED BY generate_classes.py
class ChiseledSandstone extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCChiseledSandstone FILE="Textures\MCChiseledSandstone.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCChiseledSandstone'
}
