// AUTO-GENERATED BY generate_classes.py
class Clay extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCClay FILE="Textures\MCClay.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCClay'
}
