// AUTO-GENERATED BY generate_classes.py
class CoalBlock extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCCoalBlock FILE="Textures\MCCoalBlock.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCCoalBlock'
    PlaceSoundFamily=Stone
}
