// AUTO-GENERATED BY generate_classes.py
class CoalOre extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCCoalOre FILE="Textures\MCCoalOre.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCCoalOre'
    PlaceSoundFamily=Stone
}
