// AUTO-GENERATED BY generate_classes.py
class CoarseDirt extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCCoarseDirt FILE="Textures\MCCoarseDirt.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCCoarseDirt'
    PlaceSoundFamily=Grass
}
