// AUTO-GENERATED BY generate_classes.py
class Cobblestone extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCCobblestone FILE="Textures\MCCobblestone.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCCobblestone'
}
