// AUTO-GENERATED BY generate_classes.py
class CommandBlock extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCCommandBlock FILE="Textures\MCCommandBlock.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCCommandBlock'
    PlaceSoundFamily=Stone
}
