// AUTO-GENERATED BY generate_classes.py
class CrackedStoneBricks extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCCrackedStoneBricks FILE="Textures\MCCrackedStoneBricks.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCCrackedStoneBricks'
}
