// AUTO-GENERATED BY generate_classes.py
class CraftingTable extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCCraftingTable FILE="Textures\MCCraftingTable.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCCraftingTable'
}
