// AUTO-GENERATED BY generate_classes.py
class CyanTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCCyanTerracotta FILE="Textures\MCCyanTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCCyanTerracotta'
    PlaceSoundFamily=Stone
}
