// AUTO-GENERATED BY generate_classes.py
class CyanGlazedTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCCyanGlazedTerracotta FILE="Textures\MCCyanGlazedTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCCyanGlazedTerracotta'
    PlaceSoundFamily=Stone
}
