// AUTO-GENERATED BY generate_classes.py
class CyanConcrete extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCCyanConcrete FILE="Textures\MCCyanConcrete.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCCyanConcrete'
    PlaceSoundFamily=Stone
}
