// AUTO-GENERATED BY generate_classes.py
class CyanConcretePowder extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCCyanConcretePowder FILE="Textures\MCCyanConcretePowder.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCCyanConcretePowder'
    PlaceSoundFamily=Sand
}
