// AUTO-GENERATED BY generate_classes.py
class CyanShulkerBox extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCCyanShulkerBox FILE="Textures\MCCyanShulkerBox.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCCyanShulkerBox'
}
