// AUTO-GENERATED BY generate_classes.py
class CyanWool extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCCyanWool FILE="Textures\MCCyanWool.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCCyanWool'
    PlaceSoundFamily=Cloth
}
