// AUTO-GENERATED BY generate_classes.py
class CyanStainedGlass extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCCyanStainedGlass FILE="Textures\MCCyanStainedGlass.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCCyanStainedGlass'
    PlaceSoundFamily=Stone
    Style=STY_Masked
}
