// AUTO-GENERATED BY generate_classes.py
class DarkOakLeaves extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCDarkOakLeaves FILE="Textures\MCDarkOakLeaves.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCDarkOakLeaves'
    PlaceSoundFamily=Grass
    Style=STY_Masked
}
