// AUTO-GENERATED BY generate_classes.py
class DarkPrismarine extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCDarkPrismarine FILE="Textures\MCDarkPrismarine.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCDarkPrismarine'
    PlaceSoundFamily=Stone
}
