// AUTO-GENERATED BY generate_classes.py
class DarkOakLog extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCDarkOakLog FILE="Textures\MCDarkOakLog.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCDarkOakLog'
}
