// AUTO-GENERATED BY generate_classes.py
class DarkOakPlanks extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCDarkOakPlanks FILE="Textures\MCDarkOakPlanks.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCDarkOakPlanks'
}
