// AUTO-GENERATED BY generate_classes.py
class DiamondBlock extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCDiamondBlock FILE="Textures\MCDiamondBlock.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCDiamondBlock'
    PlaceSoundFamily=Stone
}
