// AUTO-GENERATED BY generate_classes.py
class DiamondOre extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCDiamondOre FILE="Textures\MCDiamondOre.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCDiamondOre'
    PlaceSoundFamily=Stone
}
