// AUTO-GENERATED BY generate_classes.py
class Diorite extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCDiorite FILE="Textures\MCDiorite.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCDiorite'
}
