// AUTO-GENERATED BY generate_classes.py
class Dirt extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCDirt FILE="Textures\MCDirt.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCDirt'
    PlaceSoundFamily=Grass
}
