// AUTO-GENERATED BY generate_classes.py
class Dispenser extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCDispenser FILE="Textures\MCDispenser.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCDispenser'
}
