// AUTO-GENERATED BY generate_classes.py
class DoubleDarkOakWoodSlab extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCDoubleDarkOakWoodSlab FILE="Textures\MCDoubleDarkOakWoodSlab.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCDoubleDarkOakWoodSlab'
}
