// AUTO-GENERATED BY generate_classes.py
class DoubleBrickSlab extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCDoubleBrickSlab FILE="Textures\MCDoubleBrickSlab.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCDoubleBrickSlab'
    PlaceSoundFamily=Stone
}
