// AUTO-GENERATED BY generate_classes.py
class DoubleCobblestoneSlab extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCDoubleCobblestoneSlab FILE="Textures\MCDoubleCobblestoneSlab.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCDoubleCobblestoneSlab'
}
