// AUTO-GENERATED BY generate_classes.py
class DoubleJungleWoodSlab extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCDoubleJungleWoodSlab FILE="Textures\MCDoubleJungleWoodSlab.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCDoubleJungleWoodSlab'
    PlaceSoundFamily=Wood
}
