// AUTO-GENERATED BY generate_classes.py
class DoubleSpruceWoodSlab extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCDoubleSpruceWoodSlab FILE="Textures\MCDoubleSpruceWoodSlab.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCDoubleSpruceWoodSlab'
}
