// AUTO-GENERATED BY generate_classes.py
class DoubleNetherBrickSlab extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCDoubleNetherBrickSlab FILE="Textures\MCDoubleNetherBrickSlab.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCDoubleNetherBrickSlab'
}
