// AUTO-GENERATED BY generate_classes.py
class DoubleAcaciaWoodSlab extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCDoubleAcaciaWoodSlab FILE="Textures\MCDoubleAcaciaWoodSlab.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCDoubleAcaciaWoodSlab'
}
