// AUTO-GENERATED BY generate_classes.py
class DoubleStoneBrickSlab extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCDoubleStoneBrickSlab FILE="Textures\MCDoubleStoneBrickSlab.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCDoubleStoneBrickSlab'
    PlaceSoundFamily=Stone
}
