// AUTO-GENERATED BY generate_classes.py
class DoubleRedSandstoneSlab extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCDoubleRedSandstoneSlab FILE="Textures\MCDoubleRedSandstoneSlab.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCDoubleRedSandstoneSlab'
}
