// AUTO-GENERATED BY generate_classes.py
class DoubleOakWoodSlab extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCDoubleOakWoodSlab FILE="Textures\MCDoubleOakWoodSlab.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCDoubleOakWoodSlab'
}
