// AUTO-GENERATED BY generate_classes.py
class DoubleQuartzSlab extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCDoubleQuartzSlab FILE="Textures\MCDoubleQuartzSlab.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCDoubleQuartzSlab'
    PlaceSoundFamily=Stone
}
