// AUTO-GENERATED BY generate_classes.py
class DoubleSandstoneSlab extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCDoubleSandstoneSlab FILE="Textures\MCDoubleSandstoneSlab.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCDoubleSandstoneSlab'
}
