// AUTO-GENERATED BY generate_classes.py
class DoubleStoneSlab extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCDoubleStoneSlab FILE="Textures\MCDoubleStoneSlab.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCDoubleStoneSlab'
}
