// AUTO-GENERATED BY generate_classes.py
class DoubleBirchWoodSlab extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCDoubleBirchWoodSlab FILE="Textures\MCDoubleBirchWoodSlab.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCDoubleBirchWoodSlab'
    PlaceSoundFamily=Wood
}
