// AUTO-GENERATED BY generate_classes.py
class Dropper extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCDropper FILE="Textures\MCDropper.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCDropper'
    PlaceSoundFamily=Stone
}
