// AUTO-GENERATED BY generate_classes.py
class EmeraldBlock extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCEmeraldBlock FILE="Textures\MCEmeraldBlock.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCEmeraldBlock'
}
