// AUTO-GENERATED BY generate_classes.py
class EmeraldOre extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCEmeraldOre FILE="Textures\MCEmeraldOre.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCEmeraldOre'
}
