// AUTO-GENERATED BY generate_classes.py
class EndStoneBricks extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCEndStoneBricks FILE="Textures\MCEndStoneBricks.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCEndStoneBricks'
    PlaceSoundFamily=Stone
}
