// AUTO-GENERATED BY generate_classes.py
class EndStone extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCEndStone FILE="Textures\MCEndStone.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCEndStone'
}
