// AUTO-GENERATED BY generate_classes.py
class FrostedIce extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCFrostedIce FILE="Textures\MCFrostedIce.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCFrostedIce'
    Style=STY_Masked
}
