// AUTO-GENERATED BY generate_classes.py
class Furnace extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCFurnace FILE="Textures\MCFurnace.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCFurnace'
}
