// AUTO-GENERATED BY generate_classes.py
class Glass extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCGlass FILE="Textures\MCGlass.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCGlass'
    PlaceSoundFamily=Stone
    Style=STY_Masked
}
