// AUTO-GENERATED BY generate_classes.py
class Glowstone extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCGlowstone FILE="Textures\MCGlowstone.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCGlowstone'
}
