// AUTO-GENERATED BY generate_classes.py
class GlowingRedstoneOre extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCGlowingRedstoneOre FILE="Textures\MCGlowingRedstoneOre.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCGlowingRedstoneOre'
}
