// AUTO-GENERATED BY generate_classes.py
class GoldOre extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCGoldOre FILE="Textures\MCGoldOre.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCGoldOre'
}
