// AUTO-GENERATED BY generate_classes.py
class GoldBlock extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCGoldBlock FILE="Textures\MCGoldBlock.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCGoldBlock'
}
