// AUTO-GENERATED BY generate_classes.py
class Granite extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCGranite FILE="Textures\MCGranite.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCGranite'
    PlaceSoundFamily=Stone
}
