// AUTO-GENERATED BY generate_classes.py
class Grass extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCGrass FILE="Textures\MCGrass.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCGrass'
    PlaceSoundFamily=Grass
}
