// AUTO-GENERATED BY generate_classes.py
class Gravel extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCGravel FILE="Textures\MCGravel.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCGravel'
    PlaceSoundFamily=Gravel
}
