// AUTO-GENERATED BY generate_classes.py
class GrayShulkerBox extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCGrayShulkerBox FILE="Textures\MCGrayShulkerBox.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCGrayShulkerBox'
    PlaceSoundFamily=Stone
}
