// AUTO-GENERATED BY generate_classes.py
class GrayConcrete extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCGrayConcrete FILE="Textures\MCGrayConcrete.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCGrayConcrete'
    PlaceSoundFamily=Stone
}
