// AUTO-GENERATED BY generate_classes.py
class GrayGlazedTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCGrayGlazedTerracotta FILE="Textures\MCGrayGlazedTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCGrayGlazedTerracotta'
    PlaceSoundFamily=Stone
}
