// AUTO-GENERATED BY generate_classes.py
class GrayTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCGrayTerracotta FILE="Textures\MCGrayTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCGrayTerracotta'
    PlaceSoundFamily=Stone
}
