// AUTO-GENERATED BY generate_classes.py
class GrayConcretePowder extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCGrayConcretePowder FILE="Textures\MCGrayConcretePowder.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCGrayConcretePowder'
    PlaceSoundFamily=Sand
}
