// AUTO-GENERATED BY generate_classes.py
class GrayWool extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCGrayWool FILE="Textures\MCGrayWool.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCGrayWool'
    PlaceSoundFamily=Cloth
}
