// AUTO-GENERATED BY generate_classes.py
class GrayStainedGlass extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCGrayStainedGlass FILE="Textures\MCGrayStainedGlass.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCGrayStainedGlass'
    PlaceSoundFamily=Stone
    Style=STY_Masked
}
