// AUTO-GENERATED BY generate_classes.py
class GreenConcretePowder extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCGreenConcretePowder FILE="Textures\MCGreenConcretePowder.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCGreenConcretePowder'
    PlaceSoundFamily=Sand
}
