// AUTO-GENERATED BY generate_classes.py
class GreenGlazedTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCGreenGlazedTerracotta FILE="Textures\MCGreenGlazedTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCGreenGlazedTerracotta'
    PlaceSoundFamily=Stone
}
