// AUTO-GENERATED BY generate_classes.py
class GreenShulkerBox extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCGreenShulkerBox FILE="Textures\MCGreenShulkerBox.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCGreenShulkerBox'
    PlaceSoundFamily=Stone
}
