// AUTO-GENERATED BY generate_classes.py
class GreenConcrete extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCGreenConcrete FILE="Textures\MCGreenConcrete.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCGreenConcrete'
}
