// AUTO-GENERATED BY generate_classes.py
class GreenStainedGlass extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCGreenStainedGlass FILE="Textures\MCGreenStainedGlass.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCGreenStainedGlass'
    PlaceSoundFamily=Stone
    Style=STY_Masked
}
