// AUTO-GENERATED BY generate_classes.py
class GreenTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCGreenTerracotta FILE="Textures\MCGreenTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCGreenTerracotta'
    PlaceSoundFamily=Stone
}
