// AUTO-GENERATED BY generate_classes.py
class GreenWool extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCGreenWool FILE="Textures\MCGreenWool.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCGreenWool'
    PlaceSoundFamily=Cloth
}
