// AUTO-GENERATED BY generate_classes.py
class HayBale extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCHayBale FILE="Textures\MCHayBale.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCHayBale'
}
