// AUTO-GENERATED BY generate_classes.py
class Ice extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCIce FILE="Textures\MCIce.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCIce'
    Style=STY_Masked
}
