// AUTO-GENERATED BY generate_classes.py
class InfestedChiseledStoneBricks extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCInfestedChiseledStoneBricks FILE="Textures\MCInfestedChiseledStoneBricks.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCInfestedChiseledStoneBricks'
    PlaceSoundFamily=Stone
}
