// AUTO-GENERATED BY generate_classes.py
class InfestedCrackedStoneBricks extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCInfestedCrackedStoneBricks FILE="Textures\MCInfestedCrackedStoneBricks.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCInfestedCrackedStoneBricks'
    PlaceSoundFamily=Stone
}
