// AUTO-GENERATED BY generate_classes.py
class InfestedStone extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCInfestedStone FILE="Textures\MCInfestedStone.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCInfestedStone'
}
