// AUTO-GENERATED BY generate_classes.py
class InfestedMossyStoneBricks extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCInfestedMossyStoneBricks FILE="Textures\MCInfestedMossyStoneBricks.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCInfestedMossyStoneBricks'
}
