// AUTO-GENERATED BY generate_classes.py
class InfestedCobblestone extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCInfestedCobblestone FILE="Textures\MCInfestedCobblestone.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCInfestedCobblestone'
}
