// AUTO-GENERATED BY generate_classes.py
class InfestedStoneBricks extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCInfestedStoneBricks FILE="Textures\MCInfestedStoneBricks.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCInfestedStoneBricks'
}
