// AUTO-GENERATED BY generate_classes.py
class IronOre extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCIronOre FILE="Textures\MCIronOre.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCIronOre'
    PlaceSoundFamily=Stone
}
