// AUTO-GENERATED BY generate_classes.py
class IronBlock extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCIronBlock FILE="Textures\MCIronBlock.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCIronBlock'
    PlaceSoundFamily=Stone
}
