// AUTO-GENERATED BY generate_classes.py
class JackOLantern extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCJackOLantern FILE="Textures\MCJackOLantern.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCJackOLantern'
}
