// AUTO-GENERATED BY generate_classes.py
class Jukebox extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCJukebox FILE="Textures\MCJukebox.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCJukebox'
}
