// AUTO-GENERATED BY generate_classes.py
class JunglePlanks extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCJunglePlanks FILE="Textures\MCJunglePlanks.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCJunglePlanks'
}
