// AUTO-GENERATED BY generate_classes.py
class JungleLog extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCJungleLog FILE="Textures\MCJungleLog.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCJungleLog'
}
