// AUTO-GENERATED BY generate_classes.py
class JungleLeaves extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCJungleLeaves FILE="Textures\MCJungleLeaves.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCJungleLeaves'
    PlaceSoundFamily=Grass
    Style=STY_Masked
}
