// AUTO-GENERATED BY generate_classes.py
class LapisBlock extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCLapisBlock FILE="Textures\MCLapisBlock.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCLapisBlock'
}
