// AUTO-GENERATED BY generate_classes.py
class LapisOre extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCLapisOre FILE="Textures\MCLapisOre.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCLapisOre'
    PlaceSoundFamily=Stone
}
