// AUTO-GENERATED BY generate_classes.py
class LightGrayStainedGlass extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCLightGrayStainedGlass FILE="Textures\MCLightGrayStainedGlass.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCLightGrayStainedGlass'
    PlaceSoundFamily=Stone
    Style=STY_Masked
}
