// AUTO-GENERATED BY generate_classes.py
class LightGrayTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCLightGrayTerracotta FILE="Textures\MCLightGrayTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCLightGrayTerracotta'
    PlaceSoundFamily=Stone
}
