// AUTO-GENERATED BY generate_classes.py
class LightBlueConcretePowder extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCLightBlueConcretePowder FILE="Textures\MCLightBlueConcretePowder.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCLightBlueConcretePowder'
    PlaceSoundFamily=Sand
}
