// AUTO-GENERATED BY generate_classes.py
class LightBlueTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCLightBlueTerracotta FILE="Textures\MCLightBlueTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCLightBlueTerracotta'
}
