// AUTO-GENERATED BY generate_classes.py
class LightGrayConcrete extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCLightGrayConcrete FILE="Textures\MCLightGrayConcrete.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCLightGrayConcrete'
    PlaceSoundFamily=Stone
}
