// AUTO-GENERATED BY generate_classes.py
class LightGrayGlazedTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCLightGrayGlazedTerracotta FILE="Textures\MCLightGrayGlazedTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCLightGrayGlazedTerracotta'
    PlaceSoundFamily=Stone
}
