// AUTO-GENERATED BY generate_classes.py
class LightBlueGlazedTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCLightBlueGlazedTerracotta FILE="Textures\MCLightBlueGlazedTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCLightBlueGlazedTerracotta'
    PlaceSoundFamily=Stone
}
