// AUTO-GENERATED BY generate_classes.py
class LightBlueConcrete extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCLightBlueConcrete FILE="Textures\MCLightBlueConcrete.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCLightBlueConcrete'
    PlaceSoundFamily=Stone
}
