// AUTO-GENERATED BY generate_classes.py
class LightBlueStainedGlass extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCLightBlueStainedGlass FILE="Textures\MCLightBlueStainedGlass.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCLightBlueStainedGlass'
    Style=STY_Masked
}
