// AUTO-GENERATED BY generate_classes.py
class LightGrayShulkerBox extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCLightGrayShulkerBox FILE="Textures\MCLightGrayShulkerBox.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCLightGrayShulkerBox'
    PlaceSoundFamily=Stone
}
