// AUTO-GENERATED BY generate_classes.py
class LightGrayWool extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCLightGrayWool FILE="Textures\MCLightGrayWool.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCLightGrayWool'
}
