// AUTO-GENERATED BY generate_classes.py
class LightGrayConcretePowder extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCLightGrayConcretePowder FILE="Textures\MCLightGrayConcretePowder.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCLightGrayConcretePowder'
}
