// AUTO-GENERATED BY generate_classes.py
class LightBlueWool extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCLightBlueWool FILE="Textures\MCLightBlueWool.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCLightBlueWool'
}
