// AUTO-GENERATED BY generate_classes.py
class LightBlueShulkerBox extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCLightBlueShulkerBox FILE="Textures\MCLightBlueShulkerBox.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCLightBlueShulkerBox'
    PlaceSoundFamily=Stone
}
