// AUTO-GENERATED BY generate_classes.py
class LimeConcretePowder extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCLimeConcretePowder FILE="Textures\MCLimeConcretePowder.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCLimeConcretePowder'
    PlaceSoundFamily=Sand
}
