// AUTO-GENERATED BY generate_classes.py
class LimeTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCLimeTerracotta FILE="Textures\MCLimeTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCLimeTerracotta'
}
