// AUTO-GENERATED BY generate_classes.py
class LimeShulkerBox extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCLimeShulkerBox FILE="Textures\MCLimeShulkerBox.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCLimeShulkerBox'
}
