// AUTO-GENERATED BY generate_classes.py
class LimeWool extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCLimeWool FILE="Textures\MCLimeWool.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCLimeWool'
}
