// AUTO-GENERATED BY generate_classes.py
class LimeConcrete extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCLimeConcrete FILE="Textures\MCLimeConcrete.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCLimeConcrete'
    PlaceSoundFamily=Stone
}
