// AUTO-GENERATED BY generate_classes.py
class LimeGlazedTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCLimeGlazedTerracotta FILE="Textures\MCLimeGlazedTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCLimeGlazedTerracotta'
    PlaceSoundFamily=Stone
}
