// AUTO-GENERATED BY generate_classes.py
class LimeStainedGlass extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCLimeStainedGlass FILE="Textures\MCLimeStainedGlass.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCLimeStainedGlass'
    PlaceSoundFamily=Stone
    Style=STY_Masked
}
