// AUTO-GENERATED BY generate_classes.py
class LitRedstoneLamp extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCLitRedstoneLamp FILE="Textures\MCLitRedstoneLamp.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCLitRedstoneLamp'
    PlaceSoundFamily=Stone
}
