// AUTO-GENERATED BY generate_classes.py
class MagentaStainedGlass extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCMagentaStainedGlass FILE="Textures\MCMagentaStainedGlass.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCMagentaStainedGlass'
    PlaceSoundFamily=Stone
    Style=STY_Masked
}
