// AUTO-GENERATED BY generate_classes.py
class MagentaConcrete extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCMagentaConcrete FILE="Textures\MCMagentaConcrete.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCMagentaConcrete'
    PlaceSoundFamily=Stone
}
