// AUTO-GENERATED BY generate_classes.py
class MagentaWool extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCMagentaWool FILE="Textures\MCMagentaWool.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCMagentaWool'
    PlaceSoundFamily=Cloth
}
