// AUTO-GENERATED BY generate_classes.py
class MagentaConcretePowder extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCMagentaConcretePowder FILE="Textures\MCMagentaConcretePowder.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCMagentaConcretePowder'
    PlaceSoundFamily=Sand
}
