// AUTO-GENERATED BY generate_classes.py
class MagentaTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCMagentaTerracotta FILE="Textures\MCMagentaTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCMagentaTerracotta'
    PlaceSoundFamily=Stone
}
