// AUTO-GENERATED BY generate_classes.py
class MagentaShulkerBox extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCMagentaShulkerBox FILE="Textures\MCMagentaShulkerBox.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCMagentaShulkerBox'
    PlaceSoundFamily=Stone
}
