// AUTO-GENERATED BY generate_classes.py
class MagentaGlazedTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCMagentaGlazedTerracotta FILE="Textures\MCMagentaGlazedTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCMagentaGlazedTerracotta'
    PlaceSoundFamily=Stone
}
