// AUTO-GENERATED BY generate_classes.py
class MagmaBlock extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCMagmaBlock FILE="Textures\MCMagmaBlock.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCMagmaBlock'
    PlaceSoundFamily=Stone
}
