// AUTO-GENERATED BY generate_classes.py
class Melon extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCMelon FILE="Textures\MCMelon.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCMelon'
    PlaceSoundFamily=Grass
}
