// AUTO-GENERATED BY generate_classes.py
class MonsterSpawner extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCMonsterSpawner FILE="Textures\MCMonsterSpawner.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCMonsterSpawner'
    Style=STY_Masked
}
