// AUTO-GENERATED BY generate_classes.py
class MossyStoneBricks extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCMossyStoneBricks FILE="Textures\MCMossyStoneBricks.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCMossyStoneBricks'
}
