// AUTO-GENERATED BY generate_classes.py
class MossyCobblestone extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCMossyCobblestone FILE="Textures\MCMossyCobblestone.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCMossyCobblestone'
    PlaceSoundFamily=Stone
}
