// AUTO-GENERATED BY generate_classes.py
class Mycelium extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCMycelium FILE="Textures\MCMycelium.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCMycelium'
}
