// AUTO-GENERATED BY generate_classes.py
class NetherWartBlock extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCNetherWartBlock FILE="Textures\MCNetherWartBlock.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCNetherWartBlock'
}
