// AUTO-GENERATED BY generate_classes.py
class Netherrack extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCNetherrack FILE="Textures\MCNetherrack.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCNetherrack'
    PlaceSoundFamily=Stone
}
