// AUTO-GENERATED BY generate_classes.py
class NetherQuartzOre extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCNetherQuartzOre FILE="Textures\MCNetherQuartzOre.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCNetherQuartzOre'
}
