// AUTO-GENERATED BY generate_classes.py
class NetherBrick extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCNetherBrick FILE="Textures\MCNetherBrick.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCNetherBrick'
    PlaceSoundFamily=Stone
}
