// AUTO-GENERATED BY generate_classes.py
class NoteBlock extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCNoteBlock FILE="Textures\MCNoteBlock.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCNoteBlock'
    PlaceSoundFamily=Wood
}
