// AUTO-GENERATED BY generate_classes.py
class OakLeaves extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCOakLeaves FILE="Textures\MCOakLeaves.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCOakLeaves'
    PlaceSoundFamily=Grass
    Style=STY_Masked
}
