// AUTO-GENERATED BY generate_classes.py
class OakLog extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCOakLog FILE="Textures\MCOakLog.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCOakLog'
}
