// AUTO-GENERATED BY generate_classes.py
class OakPlanks extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCOakPlanks FILE="Textures\MCOakPlanks.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCOakPlanks'
    PlaceSoundFamily=Wood
}
