// AUTO-GENERATED BY generate_classes.py
class Observer extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCObserver FILE="Textures\MCObserver.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCObserver'
}
