// AUTO-GENERATED BY generate_classes.py
class Obsidian extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCObsidian FILE="Textures\MCObsidian.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCObsidian'
}
