// AUTO-GENERATED BY generate_classes.py
class OrangeConcrete extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCOrangeConcrete FILE="Textures\MCOrangeConcrete.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCOrangeConcrete'
    PlaceSoundFamily=Stone
}
