// AUTO-GENERATED BY generate_classes.py
class OrangeStainedGlass extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCOrangeStainedGlass FILE="Textures\MCOrangeStainedGlass.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCOrangeStainedGlass'
    PlaceSoundFamily=Stone
    Style=STY_Masked
}
