// AUTO-GENERATED BY generate_classes.py
class OrangeGlazedTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCOrangeGlazedTerracotta FILE="Textures\MCOrangeGlazedTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCOrangeGlazedTerracotta'
}
