// AUTO-GENERATED BY generate_classes.py
class OrangeShulkerBox extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCOrangeShulkerBox FILE="Textures\MCOrangeShulkerBox.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCOrangeShulkerBox'
    PlaceSoundFamily=Stone
}
