// AUTO-GENERATED BY generate_classes.py
class OrangeConcretePowder extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCOrangeConcretePowder FILE="Textures\MCOrangeConcretePowder.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCOrangeConcretePowder'
    PlaceSoundFamily=Sand
}
