// AUTO-GENERATED BY generate_classes.py
class OrangeWool extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCOrangeWool FILE="Textures\MCOrangeWool.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCOrangeWool'
    PlaceSoundFamily=Cloth
}
