// AUTO-GENERATED BY generate_classes.py
class OrangeTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCOrangeTerracotta FILE="Textures\MCOrangeTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCOrangeTerracotta'
}
