// AUTO-GENERATED BY generate_classes.py
class PackedIce extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCPackedIce FILE="Textures\MCPackedIce.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCPackedIce'
}
