// AUTO-GENERATED BY generate_classes.py
class PinkConcretePowder extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCPinkConcretePowder FILE="Textures\MCPinkConcretePowder.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCPinkConcretePowder'
}
