// AUTO-GENERATED BY generate_classes.py
class PinkShulkerBox extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCPinkShulkerBox FILE="Textures\MCPinkShulkerBox.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCPinkShulkerBox'
}
