// AUTO-GENERATED BY generate_classes.py
class PinkGlazedTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCPinkGlazedTerracotta FILE="Textures\MCPinkGlazedTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCPinkGlazedTerracotta'
}
