// AUTO-GENERATED BY generate_classes.py
class PinkConcrete extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCPinkConcrete FILE="Textures\MCPinkConcrete.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCPinkConcrete'
}
