// AUTO-GENERATED BY generate_classes.py
class PinkStainedGlass extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCPinkStainedGlass FILE="Textures\MCPinkStainedGlass.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCPinkStainedGlass'
    PlaceSoundFamily=Stone
    Style=STY_Masked
}
