// AUTO-GENERATED BY generate_classes.py
class PinkTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCPinkTerracotta FILE="Textures\MCPinkTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCPinkTerracotta'
    PlaceSoundFamily=Stone
}
