// AUTO-GENERATED BY generate_classes.py
class PinkWool extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCPinkWool FILE="Textures\MCPinkWool.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCPinkWool'
}
