// AUTO-GENERATED BY generate_classes.py
class Piston extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCPiston FILE="Textures\MCPiston.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCPiston'
    PlaceSoundFamily=Stone
}
