// AUTO-GENERATED BY generate_classes.py
class Podzol extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCPodzol FILE="Textures\MCPodzol.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCPodzol'
}
