// AUTO-GENERATED BY generate_classes.py
class PolishedGranite extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCPolishedGranite FILE="Textures\MCPolishedGranite.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCPolishedGranite'
}
