// AUTO-GENERATED BY generate_classes.py
class PolishedAndesite extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCPolishedAndesite FILE="Textures\MCPolishedAndesite.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCPolishedAndesite'
}
