// AUTO-GENERATED BY generate_classes.py
class PolishedDiorite extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCPolishedDiorite FILE="Textures\MCPolishedDiorite.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCPolishedDiorite'
    PlaceSoundFamily=Stone
}
