// AUTO-GENERATED BY generate_classes.py
class PrismarineBricks extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCPrismarineBricks FILE="Textures\MCPrismarineBricks.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCPrismarineBricks'
    PlaceSoundFamily=Stone
}
