// AUTO-GENERATED BY generate_classes.py
class Prismarine extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCPrismarine FILE="Textures\MCPrismarine.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCPrismarine'
}
