// AUTO-GENERATED BY generate_classes.py
class Pumpkin extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCPumpkin FILE="Textures\MCPumpkin.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCPumpkin'
    PlaceSoundFamily=Grass
}
