// AUTO-GENERATED BY generate_classes.py
class PurpurBlock extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCPurpurBlock FILE="Textures\MCPurpurBlock.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCPurpurBlock'
    PlaceSoundFamily=Stone
}
