// AUTO-GENERATED BY generate_classes.py
class PurpurPillar extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCPurpurPillar FILE="Textures\MCPurpurPillar.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCPurpurPillar'
    PlaceSoundFamily=Stone
}
