// AUTO-GENERATED BY generate_classes.py
class PurpleStainedGlass extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCPurpleStainedGlass FILE="Textures\MCPurpleStainedGlass.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCPurpleStainedGlass'
    PlaceSoundFamily=Stone
    Style=STY_Masked
}
