// AUTO-GENERATED BY generate_classes.py
class PurpleConcrete extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCPurpleConcrete FILE="Textures\MCPurpleConcrete.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCPurpleConcrete'
    PlaceSoundFamily=Stone
}
