// AUTO-GENERATED BY generate_classes.py
class PurpleShulkerBox extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCPurpleShulkerBox FILE="Textures\MCPurpleShulkerBox.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCPurpleShulkerBox'
}
