// AUTO-GENERATED BY generate_classes.py
class PurpleWool extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCPurpleWool FILE="Textures\MCPurpleWool.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCPurpleWool'
}
