// AUTO-GENERATED BY generate_classes.py
class PurpleTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCPurpleTerracotta FILE="Textures\MCPurpleTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCPurpleTerracotta'
    PlaceSoundFamily=Stone
}
