// AUTO-GENERATED BY generate_classes.py
class PurpleConcretePowder extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCPurpleConcretePowder FILE="Textures\MCPurpleConcretePowder.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCPurpleConcretePowder'
}
