// AUTO-GENERATED BY generate_classes.py
class PurpleGlazedTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCPurpleGlazedTerracotta FILE="Textures\MCPurpleGlazedTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCPurpleGlazedTerracotta'
    PlaceSoundFamily=Stone
}
