// AUTO-GENERATED BY generate_classes.py
class PurpurDoubleSlab extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCPurpurDoubleSlab FILE="Textures\MCPurpurDoubleSlab.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCPurpurDoubleSlab'
}
