// AUTO-GENERATED BY generate_classes.py
class QuartzPillar extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCQuartzPillar FILE="Textures\MCQuartzPillar.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCQuartzPillar'
    PlaceSoundFamily=Stone
}
