// AUTO-GENERATED BY generate_classes.py
class QuartzBlock extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCQuartzBlock FILE="Textures\MCQuartzBlock.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCQuartzBlock'
    PlaceSoundFamily=Stone
}
