// AUTO-GENERATED BY generate_classes.py
class RedConcrete extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCRedConcrete FILE="Textures\MCRedConcrete.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCRedConcrete'
}
