// AUTO-GENERATED BY generate_classes.py
class RedConcretePowder extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCRedConcretePowder FILE="Textures\MCRedConcretePowder.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCRedConcretePowder'
    PlaceSoundFamily=Sand
}
