// AUTO-GENERATED BY generate_classes.py
class RedGlazedTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCRedGlazedTerracotta FILE="Textures\MCRedGlazedTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCRedGlazedTerracotta'
    PlaceSoundFamily=Stone
}
