// AUTO-GENERATED BY generate_classes.py
class RedMushroomBlock extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCRedMushroomBlock FILE="Textures\MCRedMushroomBlock.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCRedMushroomBlock'
    PlaceSoundFamily=Grass
}
