// AUTO-GENERATED BY generate_classes.py
class RedNetherBrick extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCRedNetherBrick FILE="Textures\MCRedNetherBrick.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCRedNetherBrick'
    PlaceSoundFamily=Stone
}
