// AUTO-GENERATED BY generate_classes.py
class RedShulkerBox extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCRedShulkerBox FILE="Textures\MCRedShulkerBox.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCRedShulkerBox'
}
