// AUTO-GENERATED BY generate_classes.py
class RedstoneOre extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCRedstoneOre FILE="Textures\MCRedstoneOre.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCRedstoneOre'
    PlaceSoundFamily=Stone
}
