// AUTO-GENERATED BY generate_classes.py
class RedSand extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCRedSand FILE="Textures\MCRedSand.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCRedSand'
}
