// AUTO-GENERATED BY generate_classes.py
class RedStainedGlass extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCRedStainedGlass FILE="Textures\MCRedStainedGlass.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCRedStainedGlass'
    Style=STY_Masked
}
