// AUTO-GENERATED BY generate_classes.py
class RedSandstone extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCRedSandstone FILE="Textures\MCRedSandstone.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCRedSandstone'
    PlaceSoundFamily=Stone
}
