// AUTO-GENERATED BY generate_classes.py
class RedstoneLamp extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCRedstoneLamp FILE="Textures\MCRedstoneLamp.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCRedstoneLamp'
    PlaceSoundFamily=Stone
}
