// AUTO-GENERATED BY generate_classes.py
class RedstoneBlock extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCRedstoneBlock FILE="Textures\MCRedstoneBlock.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCRedstoneBlock'
}
