// AUTO-GENERATED BY generate_classes.py
class RedTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCRedTerracotta FILE="Textures\MCRedTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCRedTerracotta'
    PlaceSoundFamily=Stone
}
