// AUTO-GENERATED BY generate_classes.py
class RedWool extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCRedWool FILE="Textures\MCRedWool.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCRedWool'
}
