// AUTO-GENERATED BY generate_classes.py
class RepeatingCommandBlock extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCRepeatingCommandBlock FILE="Textures\MCRepeatingCommandBlock.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCRepeatingCommandBlock'
}
