// AUTO-GENERATED BY generate_classes.py
class Sand extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCSand FILE="Textures\MCSand.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCSand'
}
