// AUTO-GENERATED BY generate_classes.py
class Sandstone extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCSandstone FILE="Textures\MCSandstone.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCSandstone'
    PlaceSoundFamily=Stone
}
