// AUTO-GENERATED BY generate_classes.py
class SeaLantern extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCSeaLantern FILE="Textures\MCSeaLantern.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCSeaLantern'
}
