// AUTO-GENERATED BY generate_classes.py
class SlimeBlock extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCSlimeBlock FILE="Textures\MCSlimeBlock.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCSlimeBlock'
    Style=STY_Masked
}
