// AUTO-GENERATED BY generate_classes.py
class SmoothSandstone extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCSmoothSandstone FILE="Textures\MCSmoothSandstone.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCSmoothSandstone'
    PlaceSoundFamily=Stone
}
