// AUTO-GENERATED BY generate_classes.py
class SmoothRedSandstone extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCSmoothRedSandstone FILE="Textures\MCSmoothRedSandstone.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCSmoothRedSandstone'
}
