// AUTO-GENERATED BY generate_classes.py
class SnowBlock extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCSnowBlock FILE="Textures\MCSnowBlock.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCSnowBlock'
}
