// AUTO-GENERATED BY generate_classes.py
class Sponge extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCSponge FILE="Textures\MCSponge.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCSponge'
}
