// AUTO-GENERATED BY generate_classes.py
class SpruceLeaves extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCSpruceLeaves FILE="Textures\MCSpruceLeaves.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCSpruceLeaves'
    Style=STY_Masked
}
