// AUTO-GENERATED BY generate_classes.py
class SprucePlanks extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCSprucePlanks FILE="Textures\MCSprucePlanks.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCSprucePlanks'
    PlaceSoundFamily=Wood
}
