// AUTO-GENERATED BY generate_classes.py
class SpruceLog extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCSpruceLog FILE="Textures\MCSpruceLog.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCSpruceLog'
}
