// AUTO-GENERATED BY generate_classes.py
class StickyPiston extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCStickyPiston FILE="Textures\MCStickyPiston.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCStickyPiston'
    PlaceSoundFamily=Stone
}
