// AUTO-GENERATED BY generate_classes.py
class StoneBricks extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCStoneBricks FILE="Textures\MCStoneBricks.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCStoneBricks'
    PlaceSoundFamily=Stone
}
