// AUTO-GENERATED BY generate_classes.py
class Stone extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCStone FILE="Textures\MCStone.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCStone'
    PlaceSoundFamily=Stone
}
