// AUTO-GENERATED BY generate_classes.py
class StructureBlock extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCStructureBlock FILE="Textures\MCStructureBlock.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCStructureBlock'
    PlaceSoundFamily=Stone
}
