// AUTO-GENERATED BY generate_classes.py
class Terracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCTerracotta FILE="Textures\MCTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCTerracotta'
}
