// AUTO-GENERATED BY generate_classes.py
class TNT extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCTNT FILE="Textures\MCTNT.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCTNT'
}
