// AUTO-GENERATED BY generate_classes.py
class WetSponge extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCWetSponge FILE="Textures\MCWetSponge.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCWetSponge'
    PlaceSoundFamily=Grass
}
