// AUTO-GENERATED BY generate_classes.py
class WhiteTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCWhiteTerracotta FILE="Textures\MCWhiteTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCWhiteTerracotta'
    PlaceSoundFamily=Stone
}
