// AUTO-GENERATED BY generate_classes.py
class WhiteConcrete extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCWhiteConcrete FILE="Textures\MCWhiteConcrete.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCWhiteConcrete'
    PlaceSoundFamily=Stone
}
