// AUTO-GENERATED BY generate_classes.py
class WhiteShulkerBox extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCWhiteShulkerBox FILE="Textures\MCWhiteShulkerBox.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCWhiteShulkerBox'
}
