// AUTO-GENERATED BY generate_classes.py
class WhiteConcretePowder extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCWhiteConcretePowder FILE="Textures\MCWhiteConcretePowder.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCWhiteConcretePowder'
    PlaceSoundFamily=Sand
}
