// AUTO-GENERATED BY generate_classes.py
class WhiteStainedGlass extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCWhiteStainedGlass FILE="Textures\MCWhiteStainedGlass.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCWhiteStainedGlass'
    PlaceSoundFamily=Stone
    Style=STY_Masked
}
