// AUTO-GENERATED BY generate_classes.py
class WhiteGlazedTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCWhiteGlazedTerracotta FILE="Textures\MCWhiteGlazedTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCWhiteGlazedTerracotta'
    PlaceSoundFamily=Stone
}
