// AUTO-GENERATED BY generate_classes.py
class WhiteWool extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCWhiteWool FILE="Textures\MCWhiteWool.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCWhiteWool'
    PlaceSoundFamily=Cloth
}
