// AUTO-GENERATED BY generate_classes.py
class YellowWool extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCYellowWool FILE="Textures\MCYellowWool.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCYellowWool'
}
