// AUTO-GENERATED BY generate_classes.py
class YellowConcretePowder extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCYellowConcretePowder FILE="Textures\MCYellowConcretePowder.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCYellowConcretePowder'
    PlaceSoundFamily=Sand
}
