// AUTO-GENERATED BY generate_classes.py
class YellowStainedGlass extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCYellowStainedGlass FILE="Textures\MCYellowStainedGlass.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCYellowStainedGlass'
    PlaceSoundFamily=Stone
    Style=STY_Masked
}
