// AUTO-GENERATED BY generate_classes.py
class YellowGlazedTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCYellowGlazedTerracotta FILE="Textures\MCYellowGlazedTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCYellowGlazedTerracotta'
    PlaceSoundFamily=Stone
}
