// AUTO-GENERATED BY generate_classes.py
class YellowShulkerBox extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCYellowShulkerBox FILE="Textures\MCYellowShulkerBox.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCYellowShulkerBox'
}
