// AUTO-GENERATED BY generate_classes.py
class YellowConcrete extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCYellowConcrete FILE="Textures\MCYellowConcrete.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCYellowConcrete'
}
