// AUTO-GENERATED BY generate_classes.py
class YellowTerracotta extends MinecraftBlock;

#exec TEXTURE IMPORT NAME=MCYellowTerracotta FILE="Textures\MCYellowTerracotta.pcx" GROUP=Minecraft

defaultproperties
{
    Skin=Texture'MinecraftBlocks.Minecraft.MCYellowTerracotta'
    PlaceSoundFamily=Stone
}
